Repository mozilla-lockbox/lockbox-extension, pull requests merged in 2018-03, with the labels that each got.

#600 Automatically focus the filter input when the page loads; resolves #573
  src/webextension/list/containers/item-filter.js
  src/webextension/list/manage/components/app.js
  src/webextension/list/popup/components/app.js
  src/webextension/list/popup/components/item-list-panel.js
  src/webextension/list/popup/containers/current-selection.js
  src/webextension/widgets/filter-input.js
  test/unit/list/manage/components/app-test.js
  test/unit/list/popup/components/app-test.js
  test/unit/widgets/filter-input-test.js
Labels: in progress, needs-pi

#607 Updating styling of 0 entries page to reflect designs
  src/webextension/list/manage/components/intro-page.css
Labels: in progress

#601 Create a <PanelFooterButton/> and update the styles for the unlock do…
  src/webextension/images/nessie_v2.svg
  src/webextension/list/popup/components/item-list-panel.js
  src/webextension/locales/en-US/unlock.ftl
  src/webextension/unlock/components/app.css
  src/webextension/unlock/components/app.js
  src/webextension/widgets/panel.css
  src/webextension/widgets/panel.js
Labels: in progress, pi-verified

#613 Require python 3.6 in deploy stage so pip can install tornado
  .travis.yml
Labels: in progress

#567 Create/Edit Entry Details Styling Adjustments
  src/webextension/icons/hide.svg
  src/webextension/icons/show.svg
  src/webextension/list/components/item-fields.css
  src/webextension/list/components/item-fields.js
  src/webextension/list/manage/components/account-summary.css
  src/webextension/list/manage/components/edit-item-details.js
  src/webextension/list/manage/components/intro-page.css
  src/webextension/list/manage/components/item-details.css
  src/webextension/list/manage/containers/modals.js
  src/webextension/locales/en-US/list.ftl
  src/webextension/locales/en-US/widgets.ftl
  src/webextension/settings/components/app.css
  src/webextension/settings/containers/modals.js
  src/webextension/widgets/button.css
  src/webextension/widgets/button.js
  src/webextension/widgets/dialog-box.css
  src/webextension/widgets/dialog-box.js
  src/webextension/widgets/input.css
  src/webextension/widgets/password-input.js
  src/webextension/widgets/text-area.css
  test/unit/widgets/dialog-box-test.js
  test/unit/widgets/password-input-test.js
Labels: in progress, pi-verified

#562 Search bar styling adjustments (full view)
  src/webextension/icons/clear.svg
  src/webextension/icons/search.svg
  src/webextension/list/manage/components/app.css
  src/webextension/list/manage/components/app.js
  src/webextension/locales/en-US/list.ftl
  src/webextension/locales/en-US/widgets.ftl
  src/webextension/widgets/filter-input.js
  src/webextension/widgets/input.css
  test/unit/widgets/filter-input-test.js
Labels: in progress, pi-verified

#603 Make sure options_ui is fully displayed on about:addons
  src/webextension/settings/components/app.css
Labels: in progress, pi-verified

#572 Add a11y test plan to docs
  docs/accessibility-test-plan.md
Labels: accessibility, in progress

#604 Speed up branch and PR builds with Travis CI caching
  .travis.yml
Labels: chore, in progress

#608 Styling adjustments to align entry detail buttons during edit and view mode change
  src/webextension/list/components/item-fields.css
  src/webextension/list/components/item-fields.js
Labels: in progress, pi-verified

#612 Prepare 0.1.8 release
  docs/release-notes.md
  package-lock.json
  package.json
Labels: chore, in progress

#628 Fix the color of the horizontal line in the item details of the manager
  src/webextension/list/manage/components/item-details.css
Labels: in progress

#630 Move python runtime for deploy stage out of 'on' requirement
  .travis.yml
Labels: chore, in progress

#643 Downgrade Travis deploy script to fix pages deploy
  .travis.yml
Labels: chore, in progress

#647 Address #570 Post-Merge Code Review Comments
  src/webextension/background/accounts/index.js
  src/webextension/background/browser-action.js
  src/webextension/background/index.js
  test/unit/background/accounts-test.js
  test/unit/background/message-ports-test.js
  test/unit/background/telemetry-test.js
Labels: in progress

#619 DH Entry List Styling Adjustments
  src/webextension/list/components/item-list.css
  src/webextension/list/components/item-list.js
  src/webextension/list/components/item-summary.js
  src/webextension/list/manage/components/app.css
  src/webextension/list/manage/containers/all-items.css
  src/webextension/list/manage/containers/all-items.js
  src/webextension/list/popup/components/app.css
  src/webextension/unlock/components/app.css
  src/webextension/widgets/panel.css
  test/unit/list/components/item-summary-test.js
Labels: in progress, pi-verified

#668 changes to metrics
  docs/metrics.md
  src/bootstrap.js
  src/webextension/background/telemetry.js
  test/unit/background/telemetry-test.js
Labels: in progress

#655 Changing height of doorhanger to be consistent across instances
  src/webextension/list/popup/components/app.css
  src/webextension/unlock/components/app.css
Labels: in progress, pi-verified

#657 Updating entry list items, account dropdown, and quick copy button hover/press/active/focus states due to conflicting grays.
  src/webextension/list/components/item-list.css
  src/webextension/list/manage/components/account-summary.css
  src/webextension/widgets/button.css
Labels: in progress, pi-verified

#666 Improve DH integration tests and reorganize test suite
  test/integration/pages/home.py
  test/integration/tests/test_account_creation.py
  test/integration/tests/test_doorhanger.py
  test/integration/tests/test_guest_mode.py
  test/integration/tests/test_lockbox.py
Labels: in progress, needs-pi

#673 Fix wrong docs becuase syncing is not currently supported
  docs/faqs.md
Labels: in progress

#665 Create a classNames() function to handle building className props more easily
  src/webextension/common.js
  src/webextension/list/components/item-list.js
  src/webextension/list/components/item-summary.js
  src/webextension/list/containers/item-filter.js
  src/webextension/list/manage/components/account-summary.js
  src/webextension/list/manage/components/edit-item-details.js
  src/webextension/widgets/button.js
  src/webextension/widgets/copy-to-clipboard-button.js
  src/webextension/widgets/dialog-box.js
  src/webextension/widgets/field-text.js
  src/webextension/widgets/filter-input.js
  src/webextension/widgets/input.js
  src/webextension/widgets/label-text.js
  src/webextension/widgets/link.js
  src/webextension/widgets/panel.js
  src/webextension/widgets/password-input.js
  src/webextension/widgets/scrolling-list.js
  src/webextension/widgets/stack.js
  src/webextension/widgets/text-area.js
  src/webextension/widgets/toolbar.js
  test/unit/mocks/l10n.js
Labels: in progress, pi-verified

#680 Hide "clear" button on filter when there is no input
  src/webextension/widgets/filter-input.js
  src/webextension/widgets/input.css
  test/unit/widgets/filter-input-test.js
Labels: in progress

#678 Prepare 0.1.9 release
  docs/release-notes.md
  package-lock.json
  package.json
Labels: chore, in progress

#677 Updated CODEOWNERS to explicitly assign integration test ownership
  docs/CODEOWNERS
Labels: chore, in progress
