Repository mozilla-lockbox/lockbox-extension, pull requests merged in 2018-02, with the labels that each got.

#543 Fix: guest mode does not work on restart
  src/webextension/background/index.js
Labels: in progress, pi-verified

#546 pin and ignore to eslint-plugin-mozilla@0.6.0
  package-lock.json
  package.json
  src/bootstrap.js
  test/unit/mocks/xpcom.js
Labels: in progress, pi-verified

#549 Styling adjustments for the account dropdown.
  src/webextension/icons/account.svg
  src/webextension/icons/options.svg
  src/webextension/icons/signout.svg
  src/webextension/list/manage/components/account-summary.css
  src/webextension/list/manage/components/account-summary.js
  src/webextension/widgets/link.css
  src/webextension/widgets/toolbar.css
  test/unit/list/manage/components/account-summary-test.js
  test/unit/list/manage/containers/current-account-summary-test.js
Labels: in progress, pi-verified

#558 Update Version and Release Notes to 0.1.7-alpha
  docs/release-notes.md
  package-lock.json
  package.json
Labels: in progress, pi-verified

#559 Publish 0.1.7-alpha
  docs/release-notes.md
  package-lock.json
  package.json
  src/webextension/background/accounts/index.js
  src/webextension/background/index.js
  src/webextension/background/message-ports.js
  src/webextension/icons/account.svg
  src/webextension/icons/options.svg
  src/webextension/icons/signout.svg
  src/webextension/list/manage/components/account-summary.css
  src/webextension/list/manage/components/account-summary.js
  src/webextension/widgets/link.css
  src/webextension/widgets/toolbar.css
  test/unit/background/accounts-test.js
  test/unit/list/manage/components/account-summary-test.js
  test/unit/list/manage/containers/current-account-summary-test.js
  test/unit/mocks/xpcom.js
Labels: in progress, pi-verified

#566 chore(package): update stylelint to version 9.1.1
  package.json
Labels: greenkeeper, in progress, no-pi

#552 Add Support For Telemetry Scalars; Update Metrics.md
  docs/metrics.md
  src/bootstrap.js
  src/webextension/background/message-ports.js
  src/webextension/background/telemetry.js
  test/unit/background/telemetry-test.js
  test/unit/bootstrap-test.js
  test/unit/mocks/xpcom.js
Labels: in progress, pi-verified

#507 Provide documentation about how to post PRs
  docs/.dir-locals.el
  docs/contributing.md
Labels: backlog

#570 Ensure FxA account is stored always
  src/webextension/background/accounts/index.js
  src/webextension/background/browser-action.js
  src/webextension/background/datastore.js
  src/webextension/background/index.js
  src/webextension/background/message-ports.js
  test/unit/background/accounts-test.js
Labels: in progress, pi-verified

#571 Update Version and Release Notes to 0.1.7-alpha1
  docs/release-notes.md
  package-lock.json
  package.json
Labels: in progress, pi-verified

#574 Publish 0.1.7-alpha1
  docs/release-notes.md
  package-lock.json
  package.json
  src/webextension/background/accounts/index.js
  src/webextension/background/browser-action.js
  src/webextension/background/datastore.js
  src/webextension/background/index.js
  src/webextension/background/message-ports.js
  test/unit/background/accounts-test.js
Labels: in progress, pi-verified

#560 Updated text color of entry list empty state for better contrast
  src/webextension/list/components/item-list.css
Labels: in progress, pi-verified

#596 Include whitespace in item fields so new lines are output
  src/webextension/widgets/input.css
Labels: in progress, pi-verified
